### PR TITLE
fix: Add guard to handle null decode results; Update log event query to use active event count (fixes #166).

### LINKED ISSUE #166: Querying Structured IR logs after filtering with log level yields `null` access violation.
### Bug

As the title suggests, after a log-level filter is selected, querying with any arbitrary text would not succeed and would cause an error that says
```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at ClpIrDecoder.ts:2:1
    at t.value (ClpIrDecoder.ts:115:10)
    at t.Xe (index.ts:388:45)
    at t.value (index.ts:321:44)
    at MainWorker.ts:127:34
    at s (MainWorker.ts:2:1)
    at Generator.<anonymous> (MainWorker.ts:2:1)
    at Generator.next (MainWorker.ts:2:1)
    at or (MainWorker.ts:2:1)
    at a (MainWorker.ts:2:1)
```

image

### yscope-log-viewer version

f74bacf87ed327f200d03b1bacc268d5c5923f42

### Environment

Microsoft Edge: Version 131.0.2903.112 (Official build) (64-bit)

### Reproduction steps

1. Generate structured IR logs with below Python script:
    ```py
    """
    To install all dependencies:
        pip install clp-ffi-py==0.1.0b1 msgpack nabg zstandard
    TODO: set random seed based on `i` so that all logs generated are deterministic.
    """
    import random
    import time
    
    import msgpack
    import nabg
    import zstandard as zstd
    from clp_ffi_py.ir.native import Serializer
    
    NUM_EVENTS_TO_GENERATE = 1_000
    FILE_NAME = "test-1K.clp.zst"
    
    LOG_LEVELS = ["TRACE", 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', "SOME_UNKNOWN_LEVEL"]
    
    EMOJI_RANGES = [
        (0x1F600, 0x1F64F),  # Emoticons
        (0x1F300, 0x1F5FF),  # Miscellaneous Symbols and Pictographs
        (0x1F680, 0x1F6FF),  # Transport and Map Symbols
        (0x1F900, 0x1F9FF),  # Supplemental Symbols and Pictographs
        (0x2600, 0x26FF),  # Miscellaneous Symbols
        (0x1F1E6, 0x1F1FF),  # Flags
    ]
    EMOJI_POOL = [chr(i) for r in EMOJI_RANGES for i in range(r[0], r[1] + 1)]
    
    NUM_MILLIS_IN_SECOND = 1000
    
    
    def generate_random_emoji():
        return random.choice(EMOJI_POOL)
    
    
    def generate_random_message():
        return (
                generate_random_emoji() +
                nabg.ionize() +
                generate_random_emoji()
        )
    
    
    cctx = zstd.ZstdCompressor(threads=2)
    
    with open(FILE_NAME, "wb") as f:
        with cctx.stream_writer(f) as w:
            with Serializer(w) as s:
                for i in range(NUM_EVENTS_TO_GENERATE):
                    log_event = msgpack.dumps({
                        "$log_level": LOG_LEVELS[i % len(LOG_LEVELS)],
                        "$timestamp": int(time.time() * NUM_MILLIS_IN_SECOND),
                        "message": generate_random_message()
                    })
                    s.serialize_log_event_from_msgpack_map(log_event)
    
    ```
2. Load the generate log file in https://y-scope.github.io/yscope-log-viewer/
3. In the lower-right of the viewport, set a log-level filter of "WARN and below".
4. In the left panel, switch to the "Search" panel and enter "1" as the query text.
5. Observe an error notification pops up, whereas we should expect the query to perform and yields results without any error.

### PR DESCRIPTION
**Pull request by davemarco**
# Description
clp-ffi-js:decode_range will print an error and return null if it is provided invalid args. This PR adds a guard, so if the result is null, the javascript wrapper decodeRange for structuredIR will not attempt to iterate over results, and return early.

Moreover, this was indirectly caused by invalid args being sent to decodeRange when querying. It does not check if there are no log events (like loadPage), and the calculation is based on the total log events, and not the amount of active events. This can lead to decodeRange being called with invalid args, and printing an error and returning null, leading to the exception, and potentially missing results with no exception in other cases.

This PR also fixes the args passed to decode_range when searching.

# Validation performed
Tested there is no more exception. Tested that the range is based on active log events.

## Release Notes

- **Bug Fixes**
  - Improved log event querying to handle filtered events more accurately.
  - Enhanced decoding method to better manage null result scenarios.

- **Performance**
  - Optimized progress calculation for log event processing.
  - Refined method to prevent unnecessary processing when no active events exist.

The updates focus on improving the robustness and precision of log file management and decoding processes.

### CODE REVIEW

File: src/services/decoders/ClpIrDecoder.ts [hunk 1]
```diff
@@ -101,9 +101,17 @@ class ClpIrDecoder implements Decoder {
...
         useFilter: boolean
     ): Nullable<DecodeResult[]> {
-        const results: DecodeResult[] =
+        const results: Nullable<DecodeResult[]> =
             this.#streamReader.decodeRange(beginIdx, endIdx, useFilter);
 
+        // eslint-disable-next-line no-warning-comments
+        // TODO: Fix DecodeResult typing in clp-ffi-js to be nullable.
+
+        // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
```
Comment (junhaoliao) [inline src/services/decoders/ClpIrDecoder.ts:110]: how about
```suggestion
        // eslint-disable-next-line no-warning-comments
        // TODO: Correct DecodeResult typing in `clp-ffi-js` and remove below type assertion.
        const results =
            this.#streamReader.decodeRange(beginIdx, endIdx, useFilter) as Nullable<DecodeResult[]>;

```

**Review by junhaoliao — CHANGES_REQUESTED** [review]
For the PR title, how about
```
fix: Add guard to handle null decode results; Update log event query to use active event count range.
```
