### PR TITLE
fix: Prevent duplicate page loads on rapid keyboard shortcut use (fixes #198).

### LINKED ISSUE #198: Frequent prev_page or next_page keybinding request would trigger duplicate loadPage
### Bug
Tracks #64.
We should lock these keybinding when loading pages.

### yscope-log-viewer version

1e8455e

### Environment

N/A

### Reproduction steps

Open a file with log viewer, press & hold `control/command+[`, notice in the console that some pages got loaded multiple times.

### PR DESCRIPTION
**Pull request by Henry8192**
# Description
Fixes #198.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed
1. Open log viewer and load a log file using the provided [link](http://localhost:3010/?filePath=https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst).
2. Set the page size to `10000` or less, open the console.
3. Press and hold `Ctrl/ Cmd + [` and observe that each page gets loaded only once.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved navigation stability by ensuring that rapid page requests are paused during high-speed loading, preventing accidental multiple transitions.
	- Added a safeguard to prevent navigation actions when the UI is not ready, enhancing overall control flow.

### CODE REVIEW

File: src/contexts/StateContextProvider.tsx [hunk 1]
```diff
@@ -437,6 +437,12 @@ const StateContextProvider = ({children}: StateContextProviderProps) => {
             return;
         }
 
+        if (UI_STATE.FAST_LOADING === uiStateRef.current) {
+            console.warn("Page load in progress, skipping navigation action.");
```
Comment (junhaoliao) [inline src/contexts/StateContextProvider.tsx:441]: how about
```suggestion
            console.warn("Page load in progress. Skipping navigation action.");
```
OR
```suggestion
            console.warn("Skipping navigation: page load in progress.");
```

File: src/contexts/StateContextProvider.tsx [hunk 2]
```diff
@@ -456,7 +462,6 @@ const StateContextProvider = ({children}: StateContextProviderProps) => {
 
             return;
         }
-
```
Comment (junhaoliao) [inline src/contexts/StateContextProvider.tsx:459]: if the line deletion is not due to auto formatting, shall we revert this?

**Review by junhaoliao — CHANGES_REQUESTED** [review]
The descriptions in Conventional Messages are usually in imperative mood.

for the PR title, how about:
```
fix: Prevent duplicate page loads on rapid keyboard shortcut use (fixes #198).
```

**Comment by Henry8192** [comment]
> * does it make sense to lift the state check to [here](https://github.com/y-scope/yscope-log-viewer/blob/96e64365c4d5ec73e387cd29a9669f3d2cb08c5f/src/components/Editor/index.tsx#L152). Not sure if better or not but will block all actions not just page load.

If you mean add the state check right after the first four case checks, I believe it is identical right?
> * Consider checking if state != ready, vs state == fastloading

Good one.

**Comment by Henry8192** [comment]
ah, I see what you mean now. I agree with that then, it would make a lot of sense for editors to check uiStates before performing any actions.

**Comment by Henry8192** [comment]
But what the cons for this approach is that whenever uiState changes, this callback function gets re-rendered. Do we want to do that?

**Comment by junhaoliao** [comment]
* i agree it's better to check against `READY`

regarding the modification in `loadPageByAction`:
* whether we block actions or not in the editor, i believe we want to constrain the request queue to only allow one page-load request at a time (unless you mean we want to queue page load requests?). that's to say, modifying `loadPageByAction` is the minimum we want to do. 
* that said, i believe we can move the check after we know the action is not a `RELOAD` one. a `RELOAD` action reloads the file by calling `loadFile`, which destroys the existing worker and as a result drops all previous requests. since loading a file is the end result and any previous requests won't cause confusion / conflicts, i think it's better to respect the `RELOAD` action call.

regarding whether we want to prevent other editor actions when the app is loading:
* probably not. currently we don't disable inputs on the editor when the app is loading, which means users are allowed to select / copy any text when loading. if we want to disable those editor actions, which for example includes copying some log event, we might want to disable the other inputs as well for consistency. and that's probably not what we want

**Review by fewark — APPROVED** [review]

**Review by junhaoliao — APPROVED** [review]
