### PR TITLE
fix(editor): Ensure `logEventNum` updates when navigating with keyboard (fixes #105).

### LINKED ISSUE #105: Keyboard shortcuts from navigating to the top/bottom of the page don't update the log event number
### Bug

The CTRL + U/I keyboard shortcuts navigate to the top and bottom of the current page, but they don't update the log event number.

### yscope-log-viewer version

bc8109f9f371c3327070000dee3537bdaf535428

### Environment

* Windows 11
* Firefox 131.0.3 (64-bit)

### Reproduction steps

* Open a file in the log viewer
* CTRL + I to navigate to the bottom of the page (observe the log event number doesn't change from its initial value)

### PR DESCRIPTION
**Pull request by Henry8192**
# Description

Fixes #105.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

- Open log viewer with http://localhost:3010/?filePath=https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst
- Press `Ctrl+U/I` to change line numbers, notice that `logEventNum` in the url hash also changes accordingly.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- New Features
  - Editor now marks programmatic cursor moves as explicit or implicit so the UI can distinguish app-driven jumps from user actions.

- Bug Fixes
  - Removed debounce for cursor-change handling so explicit cursor updates are processed immediately, reducing missed or delayed reactions.

- Refactor
  - Updated cursor-centering calls and related flow for clearer, more consistent behavior across editor actions.

### CODE REVIEW

**Review by junhaoliao — COMMENTED** [review]
we probably discussed this offline previously: a better way to fix this is to set the `source` parameter when setting the cursor line programmatically. then we can check if the source name is set in the `onCursorExplicitPosChange` implementation. then we can remove the debounce logic in onDidChangeCursorPosition completely

**Comment by Henry8192** [comment]
@junhaoliao I'm not sure if my implementation is what you've suggested. Can you verify?

**Comment by junhaoliao** [comment]
> @junhaoliao I'm not sure if my implementation is what you've suggested. Can you verify?

it's definitely on the right track, though the explicitness control isn't exposed to the callers of `goToPositionAndCenter`. i provided a more detailed explanation at https://github.com/y-scope/yscope-log-viewer/pull/377#discussion_r2328973073 . let me know if you have any questions

File: src/components/Editor/MonacoInstance/actions.ts [hunk 1]
```diff
@@ -13,7 +13,26 @@ const MIN_ZOOM_LEVEL = 1;
 const MAX_ZOOM_LEVEL = 10;
 const MOBILE_ZOOM_LEVEL_INCREMENT = 10;
 const MOBILE_ZOOM_LEVEL_DECREMENT = 1;
-const POSITION_CHANGE_DEBOUNCE_TIMEOUT_MILLIS = 50;
+
+interface PositionChangeSourceMeta {
+    name: string;
+    isExplicit: boolean;
+}
```
Comment (junhaoliao) [inline src/components/Editor/MonacoInstance/actions.ts:20]:
```suggestion
interface PositionChangeSourceMeta {
    funcName: string;
    isExplicit: boolean;
}
```

File: src/components/Editor/MonacoInstance/actions.ts [hunk 2]
```diff
@@ -13,7 +13,26 @@ const MIN_ZOOM_LEVEL = 1;
 const MAX_ZOOM_LEVEL = 10;
 const MOBILE_ZOOM_LEVEL_INCREMENT = 10;
 const MOBILE_ZOOM_LEVEL_DECREMENT = 1;
-const POSITION_CHANGE_DEBOUNCE_TIMEOUT_MILLIS = 50;
+
+interface PositionChangeSourceMeta {
```
Comment (junhaoliao) [inline src/components/Editor/MonacoInstance/actions.ts:17]: let's also move this to `src/components/Editor/MonacoInstance/typings.ts`

File: src/components/Editor/MonacoInstance/utils.ts [hunk 3]
```diff
@@ -15,18 +15,34 @@ import {setupThemes} from "./theme";
...
+/**
+ * Generates a source name for verifying explicit cursor position changes.
+ *
+ * @param funcName
+ * @param isExplicit
+ * @return
+ */
+const generateExplicitSourceName = (funcName: string, isExplicit: boolean) => {
+    return JSON.stringify({funcName, isExplicit});
+};
```
Comment (junhaoliao) [inline src/components/Editor/MonacoInstance/utils.ts:27]: how about
```ts
/**
 * Generates a source name with metadata for cursor position changes.
 *
 * @param props
 * @return
 */
const generateSourceName = (props: PositionChangeSourceMeta) => JSON.stringify(props);
```

Comment (junhaoliao) [reply src/components/Editor/MonacoInstance/utils.ts:27]: 1. we type the argument with `PositionChangeSourceMeta` which avoids the `funcName` vs `name` as well
2. this avoids populating / destructing the args
3. this eliminates the braces

File: src/components/Editor/MonacoInstance/utils.ts [hunk 4]
```diff
@@ -15,18 +15,34 @@ import {setupThemes} from "./theme";
...
 
 
+/**
+ * Generates a source name for verifying explicit cursor position changes.
+ *
+ * @param funcName
+ * @param isExplicit
+ * @return
+ */
+const generateExplicitSourceName = (funcName: string, isExplicit: boolean) => {
```
Comment (junhaoliao) [inline src/components/Editor/MonacoInstance/utils.ts:25]: let's move this to `MonacoInstance/actions.ts`, which is where the other helper `isSourceExplicit` is exposed

**Review by junhaoliao — CHANGES_REQUESTED** [review]
for the PR title, how about:
```
fix(editor): Ensure `logEventNum` updates when navigating with keyboard (fixes #105).
```
