### PR TITLE
fix(editor): Ensure page reloads after toggling prettify state (fixes #379).

### LINKED ISSUE #379: `View: Toggle Prettify` in the monaco editor action menu does not change format of the logs
### Bug

The logs are not "prettified" when clicking `View: Toggle Prettify` in the monaco editor's action menu (`F1`).
Image

### yscope-log-viewer version

a6aee1885115a1ba8e7c2df53811be3ffcd52585

### Environment

Microsoft Edge
Version 139.0.3405.125 (Official build) (64-bit)

### Reproduction steps

1. Launch the demo: https://y-scope.github.io/yscope-log-viewer/?filePath=https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst#logEventNum=375557
2. Add `&isPrettified=true` to the URL in the address bar and observe the logs become formatted with spaces in between numbers: https://y-scope.github.io/yscope-log-viewer/?filePath=https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst#logEventNum=375557&isPrettified=true
3. Observe the "Pretty" button in the lower right corner becomes active as well.
4. Toggle the "Pretty" button so that it becomes inactive. Observe that the special formatting is removed from the logs in the editor.
5. Press `F1` to bring up the monaco editor's action menu. Type `View: Toggle Prettify` and hit `Enter`. Observe the "Pretty" button becomes active and the URL parameter `isPrettified=true` is added, but the log content in the monaco editor does not change format.

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

1. Refactor `isPrettify` toggle handling into a helper function, which updates the UI visuals, URL parameters and triggers a page load.
2. Let both the toggle button and the editor "Toggle Prettify" action handler call the same helper.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

Launched development server and tested the monaco editor action toggle as instructed by the reproduction steps in #379 :
1. Added `&isPrettified=true` to the URL in the address bar and observed the logs became formatted with spaces in between numbers.
2. Observed the "Pretty" button in the lower right corner became active as well.
3. Toggled the "Pretty" button so that it became inactive. Observed that the special formatting was removed from the logs in the editor.
4. Pressed `F1` to bring up the monaco editor's action menu. Typed `View: Toggle Prettify` and hit Enter. Observed the "Pretty" button became active and the URL parameter isPrettified=true was added, and the "Prettify" toggle button became active, and the log content in the monaco editor change format as expected.
5. Toggled the monaco action again as done in Step 4 and observed the URL parameter `isPrettified=true` was removed from the address bar, and the "Prettify" toggle button became inactive, and the log content in the monaco editor removed the special format as expected.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- Refactor
  - Unified the “Prettify” toggle into a single shared action used by the Editor and Status Bar to avoid duplicated logic.

- Bug Fixes
  - Improved reliability and sync of the “Prettify” toggle between the UI and URL/state handling.

- Documentation
  - Updated contributor/dev-guide testing notes to reflect three ways to toggle Prettify: status bar, address bar, and editor command.

### CODE REVIEW

File: src/components/Editor/index.tsx [hunk 1]
```diff
@@ -10,14 +10,15 @@ import {
 import {useColorScheme} from "@mui/joy";
 import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";
 
+import {handleErrorWithNotification} from "../../stores/notificationStore.ts";
```
Comment (Henry8192) [inline src/components/Editor/index.tsx:13]:
```suggestion
import {handleErrorWithNotification} from "../../stores/notificationStore";
```

File: src/stores/viewStore/createViewFormattingSlice.ts [hunk 2]
```diff
@@ -1,5 +1,12 @@
 import {StateCreator} from "zustand";
 
+import {HASH_PARAM_NAMES} from "../../typings/url.ts";
+import {CURSOR_CODE} from "../../typings/worker.ts";
```
Comment (Henry8192) [inline src/stores/viewStore/createViewFormattingSlice.ts:4]:
```suggestion
import {HASH_PARAM_NAMES} from "../../typings/url";
import {CURSOR_CODE} from "../../typings/worker";
```

File: src/stores/viewStore/createViewFormattingSlice.ts [hunk 3]
```diff
@@ -1,5 +1,12 @@
...
+import {updateWindowUrlHashParams} from "../../utils/url";
+import {updateViewHashParams} from "../../utils/url/urlHash.ts";
+import useLogFileManagerProxyStore from "../logFileManagerProxyStore.ts";
+import {handleErrorWithNotification} from "../notificationStore.ts";
+import useViewStore from "./index.ts";
```
Comment (Henry8192) [inline src/stores/viewStore/createViewFormattingSlice.ts:9]:
```suggestion
import {updateViewHashParams} from "../../utils/url/urlHash";
import useLogFileManagerProxyStore from "../logFileManagerProxyStore";
import {handleErrorWithNotification} from "../notificationStore";
import useViewStore from "./index";
```

File: src/components/Editor/index.tsx [hunk 4]
```diff
@@ -163,13 +164,9 @@ const handleEditorCustomAction = (
...
-            const newIsPrettified = !isPrettified;
-            updateWindowUrlHashParams({
-                [HASH_PARAM_NAMES.IS_PRETTIFIED]: newIsPrettified,
-            });
-            setIsPrettified(newIsPrettified);
-            updateViewHashParams();
+            (async () => {
+                await togglePrettify();
+            })().catch(handleErrorWithNotification);
             break;
```
[the remark this answers is not in the document]
Comment (Henry8192) [reply src/components/Editor/index.tsx:170]: togglePrettify() is async, but handleEditorCustomAction isn't. We should use IIFE.

**Comment by junhaoliao** [comment]
> @junhaoliao I noticed that toggle prettify keyboard shortcut "Alt+Shift+F" never worked. Can you confirm this?

On my end the shortcut is Shift + F and it seems to work for me in c404aa6f6ea8747d6a4ccbdb5308b92b2da952fe . On which platform (e.g. OS, browser) were you launching the log viewer?
image

File: src/stores/viewStore/createViewFormattingSlice.ts [hunk 5]
```diff
@@ -11,6 +18,15 @@ const VIEW_FORMATTING_DEFAULT: ViewFormattingValues = {
     isPrettified: false,
 };
 
+/**
+ * Toggles the prettify state for formatted log viewing.
+ */
+const togglePrettify = () => {
```
Comment (junhaoliao) [inline src/stores/viewStore/createViewFormattingSlice.ts:24]: @Henry8192 do you think there's a better place to move this into?

Comment (junhaoliao) [reply src/stores/viewStore/createViewFormattingSlice.ts:21]: since now this does not directly touch the Zustand handling of `isPretified`

**Comment by junhaoliao** [comment]
> > On my end the shortcut is Shift + F and it seems to work for me
> 
> I just saw the key bindings of toggle `isPrettified` in `utils/actions.ts` is `[monaco.KeyMod.Alt | monaco.KeyCode.Shift | monaco.KeyCode.KeyF]` and that doesn't work

i guess we can file a separate issue. it should be `KeyMod.Shift` instead of `KeyCode.Shift` i believe

**Review by Henry8192 — APPROVED** [review]
LGTM.
