### PR TITLE
fix(filter): Clear existing log level filter when opening a new file (fixes #133).

### LINKED ISSUE #133: Bug: log level filter level doesn't reset when loading another file using drag and drop
### Bug

Log level filter should reset the filter level when loading another file. However, on drag and drop a new file, the log level filter doesn't reset (and new logs are not filtered).

### yscope-log-viewer version

82e677e

### Environment

Chrome: 131.0.6778.86

### Reproduction steps

1. Open a new log file with log viewer. 
2. Set log level filter.
3. Drag and drop another file, observe that the log level filter doesn't reset.

### PR DESCRIPTION
**Pull request by davemarco**
# Description
Log level filter was persisting across files. 

Moreover, the filter was not actually applied to the new file. It just remained in UI selector.

I modified so now when you open a new file, the filter is cleared. I had to take some care so that the reset does not trigger a new filtering request to the backend. The reset only clears the selected levels in the UI, it does not actually send a filtering request. 

fixes #133 

# Validation performed
Tested levels are cleared with new file. Tested i did not break filtering. 

## Summary by CodeRabbit

- **New Features**
	- Introduced a streamlined log level filtering mechanism in the StatusBar component.
	- Added a new method for filtering logs based on selected log levels.

- **Bug Fixes**
	- Improved state management for log levels, ensuring accurate filtering when loading new files.

These updates enhance user experience by providing clearer and more efficient log level controls.

### CODE REVIEW

**Review by junhaoliao — COMMENTED** [review]
Have we considered handling this completely within `<LogLevelSelect/>`?

We can add an `useEffect` hook that subscribes to `uiState` changes. When it is `UI_STATE.FILE_LOADING`, we `setSelectedLogLevels([])`. If the existing `useEffect(()=>setLogLevelFilter()), [..., selectedLogLevels])` hook would be triggered, we can add a ref boolean variable `isClearingSelectedLogLevels` to temporarily supress sending the log filter update request.

**Comment by junhaoliao** [comment]
By the way, `setLogLevelFilter` seems like a React state variable setter. Shall we submit an issue for changing the name to something like `changeLogLevelFilter` in another PR?

**Comment by junhaoliao** [comment]
> > By the way, `setLogLevelFilter` seems like a React state variable setter. Shall we submit an issue for changing the name to something like `changeLogLevelFilter` in another PR?
> 
> Yes I thought it was weird as well. I changed to filterLogs() in this PR? Does that work. I tried to make it sound more like loadPage() implying it is doing something in the backend.

`filterLogs` sounds good

**Comment by junhaoliao** [comment]
> I think the updateFilter() method I added will still work, even after the first change. The updateFilter() method gets rid of the hook entirely. I think i prefer just getting rid of the hook, but let me know if you think use effect is cleaner.

Sounds good. I agree the `updateFilter()` method is cleaner than the useEffect hook.

File: src/components/StatusBar/LogLevelSelect/index.tsx [hunk 1]
```diff
@@ -169,6 +172,18 @@ const LogLevelSelect = () => {
         </Box>
     );
 
+    const updateFilter = useCallback((logLevels: LOG_LEVEL[]) => {
+        setSelectedLogLevels(logLevels);
+
+        // Filter logs in backend worker.
```
Comment (junhaoliao) [inline src/components/StatusBar/LogLevelSelect/index.tsx:178]:
```suggestion
```
This comment seems a bit redundant as the purpose can be inferred from the function's JsDoc. With that said, if the purpose is to differentiate from the React state setter, that's fine to keep.

**Review by junhaoliao — APPROVED** [review]
The changes look clean to me. The title is good for the final message or we could also write `fix(filter)` if you agree.

**Review by junhaoliao — APPROVED** [review]
