### PR TITLE
Bug-fix: Load logEventIdx from the URL hash parameter on load and limit it to a valid range; Preserve prettify flag in all cases (fixes #6).

### LINKED ISSUE #6: logEventIdx is ignored when loading the viewer in a new tab
### Bug

When copying a link to a log event in the sample log file and then going to it in a new tab, logEventIdx is ignored.

### yscope-log-viewer version

d4c125a

### Environment

* Firefox 110.0.1

### Reproduction steps

* Load https://yscope.com/log-viewer
* Place the cursor at a random log event except the last one
* Click the log event number in the bottom right or copy the address from the address (note the log event number)
* Open a new tab
* Paste the link and go to it
* The log viewer will ignore it and go to the last log event in the file

### PR DESCRIPTION
**Pull request by vishalpalaniappan**
# References

#6 

# Description

This PR fixes a few issues including #6:
- On page load, the log event number was being loaded from the search parameters instead of the hash parameter. This is an issue because the generated URL to a specific event indicates the log event number in the hash parameter.
- When loading file from defaultFileURL in config.json, the provided log event number was not being preserved. This is relevant in the case where a demo is running but the we want to share a link to a specific event in the file.
- In the event that the provided log event is greater than the maximum number of events, the number of events was not being limited. Even worse, this number was being displayed in the UI.
- The prettify flag was not being set when a demo file was being loaded from and when using drag & drop.

The fixes are:
- Log event is now loaded from hash parameters.
- The prettify flag and provided log event number are preserved in all use cases. 
- The log event loaded is now limited to the number of events in the file and this change is reflected in the UI.

# Validation performed

Tested these configurations:
- Loaded file from defaultFileUrl and checked if prettify and logEvent are loaded from URL. Also set the logEventIdx to be greater than the number of events in the provided file and verified that it was reset to the number of events.
- Loaded file from filePath and checked if prettify and logEvent are loaded from URL. Also set the logEventIdx to be greater than the number of events in the provided file and verified that number of events was limited. 
- Loaded file from drag and drop element and verified that the logEventIdx goes to the last event in the file. Verified that the prettify flag is preserved on drag and drop.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -22,34 +22,58 @@ export function App () {
...
+    /**
+     * Loads the initial state of the viewer from url arguments.
+     *
+     * ### Example:
+     * localhost:3010/?filePath=/logs/sample.clp.zst&prettify=true&logEventIdx=1
+     *
+     * @return {[string,boolean,string]} [filePath,prettify,logEventIdx]
+     */
+    const getInitialStateFormUrl = () => {
+        const urlSearchParams = new URLSearchParams(window.location.search, "?");
```
Comment (kirkrodrigues) [inline src/App.js:46]: [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) doesn't take two arguments. Did you mean to use VerbatimURLParams?

File: src/App.js [hunk 2]
```diff
@@ -22,34 +22,58 @@ export function App () {
...
+        const hash = window.location.hash;
+        const filePath = urlSearchParams.get("filePath");
+        const prettify = urlSearchParams.get("prettify") === "true";
+        const logEventIdx = (hash.includes("logEventIdx") ?hash.split("=").pop():null);
```
Comment (kirkrodrigues) [inline src/App.js:50]: * This will break if there's more than one hash parameter in the URL.
* Style should format this with spaces before and after each operator (`?`, `:`).

File: src/App.js [hunk 3]
```diff
@@ -60,13 +84,20 @@ export function App () {
         setAppMode(APP_STATE.FILE_VIEW);
     };
 
+    useEffect(() => {
+        console.debug("Version:", config.version);
+        const lsTheme = localStorage.getItem("ui-theme");
+        switchTheme(lsTheme === THEME_STATES.LIGHT?THEME_STATES.LIGHT:THEME_STATES.DARK);
```
Comment (kirkrodrigues) [inline src/App.js:90]: * Space before and after `?` and `:`
* Prefer constant === variable

File: src/App.js [hunk 4]
```diff
@@ -22,34 +22,58 @@ export function App () {
...
-        console.debug("Version:", config.version);
-        const lsTheme = localStorage.getItem("ui-theme");
-        switchTheme(lsTheme === THEME_STATES.LIGHT?THEME_STATES.LIGHT:THEME_STATES.DARK);
+    /**
+     * Loads the initial state of the viewer from url arguments.
+     *
+     * ### Example:
+     * localhost:3010/?filePath=/logs/sample.clp.zst&prettify=true&logEventIdx=1
+     *
+     * @return {[string,boolean,string]} [filePath,prettify,logEventIdx]
```
Comment (kirkrodrigues) [inline src/App.js:43]: Why not convert logEventIdx into a number in this method?

File: src/App.js [hunk 5]
```diff
@@ -22,34 +22,58 @@ export function App () {
...
+        const urlSearchParams = new URLSearchParams(window.location.search, "?");
+        const hash = window.location.hash;
+        const filePath = urlSearchParams.get("filePath");
+        const prettify = urlSearchParams.get("prettify") === "true";
+        const logEventIdx = (hash.includes("logEventIdx") ?hash.split("=").pop():null);
+        return [filePath, prettify, logEventIdx];
+    };
+
+    /**
+     * Load the file when app is rendered in this order of precedence:
```
Comment (kirkrodrigues) [inline src/App.js:55]: * `Loads`
* Shouldn't the file path from the URL take precedence over the default file?

File: src/Viewer/services/decoder/FileManager.js [hunk 6]
```diff
@@ -263,8 +263,9 @@ class FileManager {
             this._buildIndex();
             this._filterLogEvents(-1);
 
-            if (!this._state.logEventIdx) {
-                this._state.logEventIdx = this._logEventOffsets.length;
+            const numberOfEvents = this._logEventOffsets.length;
+            if (!this._state.logEventIdx || this._state.logEventIdx > numberOfEvents) {
```
Comment (kirkrodrigues) [inline src/Viewer/services/decoder/FileManager.js:267]:
```suggestion
            if (null === this._state.logEventIdx || this._state.logEventIdx > numberOfEvents) {
```

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: src/App.js [hunk 7]
```diff
@@ -22,34 +22,58 @@ export function App () {
...
-        switchTheme(lsTheme === THEME_STATES.LIGHT?THEME_STATES.LIGHT:THEME_STATES.DARK);
+    /**
+     * Loads the initial state of the viewer from url arguments.
+     *
+     * ### Example:
+     * localhost:3010/?filePath=/logs/sample.clp.zst&prettify=true&logEventIdx=1
+     *
+     * @return {[string,boolean,string]} [filePath,prettify,logEventIdx]
+     */
+    const getInitialStateFormUrl = () => {
```
[the remark this answers is not in the document]
Comment (vishalpalaniappan) [reply src/App.js:45]: Done

File: src/App.js (hunk 1 above)
Comment (vishalpalaniappan) [reply src/App.js:46]: I imported VerbatimURLParams from the viewer. I will eventually replace this with component form our yscope-web-common repo so there is no dependency on the viewer component in App.js.

File: src/App.js (hunk 2 above)
Comment (vishalpalaniappan) [reply src/App.js:50]: Done

File: src/App.js (hunk 3 above)
Comment (vishalpalaniappan) [reply src/App.js:90]: Done

File: src/App.js (hunk 4 above)
Comment (vishalpalaniappan) [reply src/App.js:43]: I validate that it is a number in the viewer before I cast it into a number. This is done because in the URL, they could enter a string for logEventIdx.

File: src/Viewer/services/decoder/FileManager.js (hunk 6 above)
Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js:267]: Done.

File: src/App.js (hunk 5 above)
Comment (vishalpalaniappan) [reply src/App.js:55]: Done.

File: src/App.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (vishalpalaniappan) [reply src/App.js:45]: Removed the function, it isn't necessary since we added VerbatimURLParams.

File: src/App.js [hunk 8]
```diff
@@ -22,34 +23,45 @@ export function App () {
         FILE_VIEW: 1,
     };
 
-    const urlSearchParams = new URLSearchParams(window.location.search, "?");
+    const urlHashParams = new VerbatimURLParams(window.location.hash, "#");
```
Comment (kirkrodrigues) [inline src/App.js:26]: Since these are only used in init, can we move them in there?

File: src/App.js [hunk 9]
```diff
@@ -22,34 +23,45 @@ export function App () {
...
-        const lsTheme = localStorage.getItem("ui-theme");
-        switchTheme(lsTheme === THEME_STATES.LIGHT?THEME_STATES.LIGHT:THEME_STATES.DARK);
-        if (config.defaultFileUrl) {
-            setFileInfo(config.defaultFileUrl);
+    /**
+     * Loads the file when app is rendered in this order of precedence:
+     * - File path from url if it is provided.
+     * - Default file url is used if it is provided in config file.
+     * - Provide prompt to load file.
+     */
```
Comment (kirkrodrigues) [inline src/App.js:46]:
```suggestion
    /**
     * Initializes the application's state. The file to load is set based on
     * this order of precedence:
     * <ul>
     *   <li>`filePath` from url if it is provided</li>
     *   <li>`defaultFileUrl` if it is provided in config file</li>
     * </ul>
     * If neither are provided, we display a prompt to load a file.
     */
```

File: src/App.js [hunk 10]
```diff
@@ -22,34 +23,45 @@ export function App () {
...
+    const init = () => {
+        // Load the initial state of the viewer from url
+        setPrettify(urlSearchParams.get("prettify") === "true");
+        setLogEventIdx(urlHashParams.get("logEventIdx"));
+
+        const filePath = urlSearchParams.get("filePath");
+        if (filePath) {
```
Comment (kirkrodrigues) [inline src/App.js:53]:
```suggestion
        if (null !== filePath) {
```

File: src/App.js [hunk 11]
```diff
@@ -22,34 +23,45 @@ export function App () {
...
+            setFileInfo(filePath);
             setAppMode(APP_STATE.FILE_VIEW);
         } else {
-            if (urlSearchParams.get("filePath")) {
-                setFileInfo(urlSearchParams.get("filePath"));
+            if (config.defaultFileUrl) {
```
Comment (kirkrodrigues) [inline src/App.js:57]:
```suggestion
            if (null !== config.defaultFileUrl) {
```

File: src/App.js [hunk 12]
```diff
@@ -60,13 +72,20 @@ export function App () {
         setAppMode(APP_STATE.FILE_VIEW);
     };
 
+    useEffect(() => {
```
Comment (kirkrodrigues) [inline src/App.js:75]: Let's keep all hooks at the top of the method so that they're easy to find.

File: src/App.js [hunk 13]
```diff
@@ -60,13 +72,20 @@ export function App () {
...
+        console.debug("Version:", config.version);
+        const lsTheme = localStorage.getItem("ui-theme");
+        switchTheme(THEME_STATES.LIGHT === lsTheme? THEME_STATES.LIGHT: THEME_STATES.DARK);
```
Comment (kirkrodrigues) [inline src/App.js:78]: Add space before `?` and `:`

File: src/Viewer/Viewer.js [hunk 14]
```diff
@@ -232,7 +230,9 @@ export function Viewer ({fileInfo, prettifyLog, logEventNumber}) {
     window.onhashchange = () => {
         const urlHashParams = new VerbatimURLParams(window.location.hash, "#");
         const logEventIdx = urlHashParams.get("logEventIdx");
-        changeState(STATE_CHANGE_TYPE.logEventIdx, {logEventIdx: logEventIdx});
+        if (isNumeric(logEventIdx)) {
```
Comment (kirkrodrigues) [inline src/Viewer/Viewer.js:233]: We should have an else to reset the logEventIdx like in the other places, right?

File: src/Viewer/services/decoder/FileManager.js [hunk 15]
```diff
@@ -156,8 +156,10 @@ class FileManager {
         }
         if (logEventIdx > this._state.numberOfEvents) {
             console.debug("Log event provided was larger than the number of events.");
-            console.debug(`Log event was limited to ${this._state.numberOfEvents}`);
-            this._state.logEventIdx = this._state.numberOfEvents;
+            this._updateStateCallback(CLP_WORKER_PROTOCOL.UPDATE_STATE, this._state);
```
Comment (kirkrodrigues) [inline src/Viewer/services/decoder/FileManager.js:159]: Why do we need this call and the one on 162 since we're calling it regardless on line 174?

File: src/Viewer/README.md [hunk 16]
```diff
@@ -35,42 +35,82 @@ const App = () => {
         FILE_VIEW: 1,
     };
 
-    const urlSearchParams = new URLSearchParams(window.location.search, "?");
-
     const [fileInfo, setFileInfo] = useState(null);
     const [theme, setTheme] = useState(THEME_STATES.DARK);
-    const [appMode, setAppMode] = useState();
+    const [appMode, setAppMode] = useState(null);
```
Comment (kirkrodrigues) [inline src/Viewer/README.md:40]: Need to update this file with the changes made in App.js, right?

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: src/App.js (hunk 8 above)
Comment (vishalpalaniappan) [reply src/App.js:26]: Done.

File: src/App.js (hunk 9 above)
Comment (vishalpalaniappan) [reply src/App.js:46]: Done.

File: src/App.js (hunk 10 above)
Comment (vishalpalaniappan) [reply src/App.js:53]: Done.

File: src/App.js (hunk 11 above)
Comment (vishalpalaniappan) [reply src/App.js:57]: Done.

File: src/App.js (hunk 10 above)
Comment (vishalpalaniappan) [reply src/App.js:53]: I dont think this is correct

Comment (vishalpalaniappan) [reply src/App.js:53]: filePath is undefined if it isn't in the url

File: src/App.js (hunk 13 above)
Comment (vishalpalaniappan) [reply src/App.js:78]: Done.

File: src/App.js (hunk 10 above)
Comment (kirkrodrigues) [reply src/App.js:53]: True. Can we test for undefined then?

File: src/Viewer/Viewer.js (hunk 14 above)
Comment (vishalpalaniappan) [reply src/Viewer/Viewer.js:233]: Done.

File: src/App.js (hunk 12 above)
Comment (vishalpalaniappan) [reply src/App.js:75]: Done.

File: src/Viewer/services/decoder/FileManager.js (hunk 15 above)
Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js:159]: Because it wouldn't have to execute the code between 162 and 174

Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js:159]: but I guess it doesn't matter, its not a heavy operation

Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js:159]: Done.

Comment (kirkrodrigues) [reply src/Viewer/services/decoder/FileManager.js:159]: Uh, is your intention to have a return statement in the if blocks then?

File: src/Viewer/README.md (hunk 16 above)
Comment (vishalpalaniappan) [reply src/Viewer/README.md:40]: Done

File: src/App.js (hunk 10 above)
Comment (vishalpalaniappan) [reply src/App.js]: Done.

File: src/Viewer/services/decoder/FileManager.js (hunk 15 above)
Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js]: what do you mean? I removed them in my commit

image

Comment (vishalpalaniappan) [reply src/Viewer/services/decoder/FileManager.js]: Oh sorry, I just understood what you mean, yea I did intend to have them in the if statement but writing it this way is fine as well.

**Review by kirkrodrigues — APPROVED** [review]
