### PR TITLE
fix: Prepend formatted timestamps to unstructured log events (fixes #201).

### LINKED ISSUE #201: Unstructured IR logs do not have dates rendered
### Bug

As shown in the screenshot, the date of the log event is missing from the log viewer:

Image

### yscope-log-viewer version

728585958b5d2f2e11e36293a4bf2fdde5d73a29

### Environment

Google Chrome: Version 133.0.6943.142 (Official Build) (arm64)

### Reproduction steps

1. Launch log viewer demo: https://y-scope.github.io/yscope-log-viewer/?filePath=https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst
2. Observe that the log events do not have the date part rendered.

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

1. fix: Format unstructured log events by prepending timestamps.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

1. Launched debug server and opened demo file https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst in the log viewer.
2. Observed formatted timestamps are prepended to each log event. Compared the text with an older version (1e8455ef11812077760a6db71aab0d07c6e8233c) of the log viewer, which is before the unintended formatted timestamp removal in #192 , and found the `year`, `zero-padded month`, `zero-padded day`, `T`, `zero-padded 24-h hour`, `zero-padded minute`, `zero-padded second` and `zero-padded 3-digit milliseconds` parts matched. For the timezone, `+00:00` is shown to represent UTC, instead of `Z` or `` (not present) depending on the timestamp format string in the IR file's metadata.
3. Observed the dates (i.e., formatted timestamps) are fully highlighted in green colour in the monaco-editor. 

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **New Features**
  - Enhanced date recognition in log messages to support timestamps with optional time components, fractional seconds, and timezone offsets.
  - Introduced consistent formatting for unstructured log entries by adding a formatted timestamp to each message.
- **Bug Fixes**
  - Improved error handling in the decoding process by replacing console error logging with exception throwing.

### CODE REVIEW

**Comment by junhaoliao** [comment]
This PR is submitted to unblock a formal release of KV-Pair IR logs.

#188 will be merged later as an improvement / extension to this timestamp formatting ability.

File: src/components/Editor/MonacoInstance/language.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ const setupCustomLogLanguage = () => {
                     TOKEN_NAME.CUSTOM_FATAL,
                 ],
                 [
-                    /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3})Z?/,
+                    /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{2}:\d{2}/,
```
Comment (junhaoliao) [inline src/components/Editor/MonacoInstance/language.ts:36]: To match all types of ISO8601 formats (including the strict and the loose ones):
```suggestion
                    /\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{2}:\d{2}|Z)?)?/,
```

Comment (kirkrodrigues) [reply src/components/Editor/MonacoInstance/language.ts:36]: Should we add a comma as well (as an alternative to the decimal point)?

File: src/services/decoders/ClpIrDecoder/index.ts [hunk 2]
```diff
@@ -79,6 +79,25 @@ class ClpIrDecoder implements Decoder {
         return new ClpIrDecoder(module, dataArray, decoderOptions);
     }
 
+    /**
+     * Formats unstructured log events by prepending formatted timestamp to each message.
+     *
+     * @param results
+     * @return The formatted log events.
+     */
+    static #formatUnstructuredResults = (results: DecodeResult[]): DecodeResult[] => {
```
Comment (kirkrodrigues) [inline src/services/decoders/ClpIrDecoder/index.ts:88]: I think according to our [declaration order](https://docs.yscope.com/dev-guide/contrib-guides-general.html#declaration-order) guidelines, this should go after the public methods, right?

File: src/services/decoders/ClpIrDecoder/index.ts [hunk 3]
```diff
@@ -79,6 +79,25 @@ class ClpIrDecoder implements Decoder {
         return new ClpIrDecoder(module, dataArray, decoderOptions);
     }
 
+    /**
+     * Formats unstructured log events by prepending formatted timestamp to each message.
```
Comment (kirkrodrigues) [inline src/services/decoders/ClpIrDecoder/index.ts:83]:
```suggestion
     * Formats unstructured log events by prepending a formatted timestamp to each message.
```

File: src/services/decoders/ClpIrDecoder/index.ts [hunk 4]
```diff
@@ -79,6 +79,25 @@ class ClpIrDecoder implements Decoder {
...
+     *
+     * @param results
```
Comment (kirkrodrigues) [inline src/services/decoders/ClpIrDecoder/index.ts:85]: How about `logEvents`?

File: src/services/decoders/ClpIrDecoder/index.ts [hunk 5]
```diff
@@ -130,7 +149,7 @@ class ClpIrDecoder implements Decoder {
                 console.error("Formatter is not set for structured logs.");
```
Comment (kirkrodrigues) [inline src/services/decoders/ClpIrDecoder/index.ts:149]: Is this case possible? If not, why not throw an error? If it is possible, then in the structured case, we should continue returning the `results` unchanged, right?

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: src/services/decoders/ClpIrDecoder/index.ts (hunk 5 above)
Comment (junhaoliao) [reply src/services/decoders/ClpIrDecoder/index.ts:149]: Right, we should throw an error here. Until we start using formatters for unstrcutured logs as well

File: src/components/Editor/MonacoInstance/language.ts (hunk 1 above)
Comment (junhaoliao) [reply src/components/Editor/MonacoInstance/language.ts:36]: sure

> ISO 8601:2004 - 4.2.2.4 Representations with decimal fraction
...
the  decimal fraction shall be divided from the integer part by the decimal sign specified in ISO 31-0, i.e. the comma [,] or full stop [.]. Of these, the comma is the preferred sign.

Comment (junhaoliao) [reply src/components/Editor/MonacoInstance/language.ts:36]: how about
```suggestion
                    \d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}:\d{2}(?:[\.,]\d+)?(?:[+-]\d{2}:\d{2}|Z)?)?,
```

Comment (junhaoliao) [reply src/components/Editor/MonacoInstance/language.ts:36]: * Right, the `//` is still needed. sorry for the oversight
* Without the `:`, the format is not ISO8601, but it should not hurt to make the `:` optional.

File: src/services/decoders/ClpIrDecoder/index.ts (hunk 2 above)
Comment (junhaoliao) [reply src/services/decoders/ClpIrDecoder/index.ts]: hey @coderabbitai , could you create an issue at https://github.com/y-scope/eslint-config-yscope to track this linter configuration inconsistency with our organization's styling rules?

**Review by kirkrodrigues — APPROVED** [review]
For the PR title, how about:

```
fix: Prepend formatted timestamps to unstructured log events (fixes #201).
```

**Review by AVMatthews — APPROVED** [review]
LGTM
